// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwmatpclurkueeguinqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bWF0cGNsdXJrdWVlZ3VpbnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzAxMjgsImV4cCI6MjA2NzY0NjEyOH0.QSpCUWopo7GEygIhR-I5Q_qHFkI6T3TJWvaosHZ_lYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
