name: finalize-auctions

on:
  schedule:
    - cron: "*/5 * * * *"   # a cada 5 minutos (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call finalize endpoint
        run: |
          curl -fsSL --retry 3 --max-time 25 \
            -X POST "https://diecastbrv2-9mtn.vercel.app/api/auctions/finalize" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
