name: finalize-auctions
on:
  schedule:
    - cron: "*/5 * * * *"   # a cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call finalize endpoint
        run: |
          curl -s -X POST "https://SEU-DOMINIO-VERCEL/api/auctions/finalize" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
